### ISSUE TITLE
Scheme always uses dhcp

### ISSUE THREAD

**Issue by Grandpa-G** [rockymeza/wifi#103]
From what I can tell, the schemes always use dhcp. Could we make it part of the option? I need static ip and this doesn't work for me.

**Comment by edras** [comment]
This is exactly what I was looking for. I need to setup static ip and this issue would be very nice.

**Comment by rockymeza** [comment]
Hi this is a great idea.  Here's where the code refers to dhcp: https://github.com/rockymeza/wifi/blob/master/wifi/scheme.py#L90

I don't have time to write this right now, but if you wanted to write a pull request that would be super awesome.

**Comment by Grandpa-G** [comment]
I am no longer using wifi.
