### ISSUE TITLE
Scheme.Save() Fails

### ISSUE THREAD

**Issue by jackfmadrid** [rockymeza/wifi#111]
I am trying to create and save a WiFi scheme however when I run program the save always fails with a permission denied error. There appears to be a scheme.py file already located under the /usr/local/lib/python2.7/dist-packages/wifi folder and the file is protected from being changed.

cell = Cell.all('wlan0')[0]
scheme = Scheme.for_cell('wlan0', 'home', cell)
scheme.save()

**Comment by melvyn-sopacua** [comment]
Triage:

* doc issue. Scheme saving should always be done as root as system files are root owned.
* bug: should support more schemes (systemd, wpa_supplicant) and integrate `sudo`.

**Comment by jackfmadrid** [comment]
I was able to get this to work doing this using the sudo command...Thx
