### ISSUE TITLE
Does not handle networks named with '-'

### ISSUE THREAD

**Issue by rsaxvc** [rockymeza/wifi#70]
I'm pretty sure the following regex from scheme.py doesn't handle multiple '-' characters:

    scheme_re = re.compile(r'iface\s+(?P<interface>wlan\d?)(?:-(?P<name>\w+))?')

For example, Scheme.find("wlan0", "WOOP-DOOP") will never find anything.

**Comment by rsaxvc** [comment]
Try this instead:
iface\s+(?P<interface>wlan\d?)(?:-(?P<name>[\-\w]+))?

**Comment by rockymeza** [comment]
Hi. Sorry for taking forever. I think this should be fixed 0.3.7
