### ISSUE TITLE
No Cell object

### ISSUE THREAD

**Issue by opensourcehiker** [rockymeza/wifi#71]
the library from pip does not appear to have the Cell object included. I get an error whenever I try and run a script with WiFi.Cell saying that Cell is not in the module. help?

**Comment by rockymeza** [comment]
can you post the relevant part of your code?

**Comment by opensourcehiker** [comment]
Just this one line of code generates an error:
![image](https://cloud.githubusercontent.com/assets/13277984/8804257/5a70308c-2f99-11e5-8ac6-1109264b11bf.png)

And this is the wifi package after I did "pip install wifi"
![image](https://cloud.githubusercontent.com/assets/13277984/8804269/6c796e9c-2f99-11e5-8b30-53891208ce51.png)

**Comment by rockymeza** [comment]
I see that you have a wifi/detect/detect.py file, it's possible that there is interference between the wifi directory in your project and the wifi library as installed.

**Comment by opensourcehiker** [comment]
Even if that is the package directory of my project? detect.py is the module where my code is going

**Comment by opensourcehiker** [comment]
I think that Eclipse is the recognizing the Python library just not the scan. py module which contains the code for the Cell class. I tried WiFi scan and it worked so I'm confused why the library won't work

**Comment by rockymeza** [comment]
Maybe you could try to rename your wifi/ directory to something else to see if it is indeed the problem.

If you are comfortable with pdb, you could also try that.

**Comment by rockymeza** [comment]
Post*

-rocky
2015年7月20日 上午7:21于 写道：

Hi,

Can you pay your code please

-rocky
2015年7月20日 上午5:04于 "Max K" <notifications@github.com>写道：

the library from pip does not appear to have the Cell object included. I
get an error whenever I try and run a script with WiFi.Cell saying that
Cell is not in the module. help?

—
Reply to this email directly or view it on GitHub
<https://github.com/rockymeza/wifi/issues/71>.

**Comment by rockymeza** [comment]
Hi,

Can you pay your code please

-rocky
2015年7月20日 上午5:04于 "Max K" <notifications@github.com>写道：

**Comment by opensourcehiker** [comment]
No its just that code that didnt work I made sure to try out the WiFi library before anything else and when I tried using the scan module I got that error there is no other code yet but there will be :)

**Comment by opensourcehiker** [comment]
So I created a new project without the /wifi/detect/ package and it worked 100%. I realize now that the src  folder of the project was added to the python path and it was using itself as the wifi package. Thanks so much it works great now!
