### ISSUE TITLE
AttributeError: 'Cell' object has no attribute 'ssid'

### ISSUE THREAD

**Issue by tlau** [rockymeza/wifi#86]
When running the `wifi` command, I intermittently get this error:

```
% wifi
Traceback (most recent call last):
  File "/usr/local/bin/wifi", line 202, in <module>
    args.func(args)
  File "/usr/local/bin/wifi", line 51, in scan_command
    print_table([[cell.signal, cell.ssid, 'protected' if cell.encrypted else 'unprotected'] for cell in Cell.all(args.interface)])
AttributeError: 'Cell' object has no attribute 'ssid'
```

I suspect there's a wireless network in my environment which doesn't broadcast SSID, or something, which causes this particular failure.

**Comment by rockymeza** [comment]
Hi!

Thanks for the bug report. Just to confirm, can you send me the output of
`iwlist wlan0 scan` please?

Thanks!

-rocky

**Comment by tlau** [comment]
Here you go:

[wlan0-scan.txt](https://github.com/rockymeza/wifi/files/92966/wlan0-scan.txt)

**Comment by rockymeza** [comment]
Hi, I just merged a fix into master, do you want to try it out?

**Comment by rockymeza** [comment]
Released https://pypi.python.org/pypi/wifi/0.3.5

**Comment by tlau** [comment]
Yep, that fixes it. Thanks!
