### ISSUE TITLE
Does not handle network names with spaces example: my network

### ISSUE THREAD

**Issue by robandr** [rockymeza/wifi#89]
Hi I am using your wifi and was very happy. But in one of my application the name of the network I was connecting to was changed from "MyNetwork" to "My Network" and wifi could not connect anymore. See the error message:

Traceback (most recent call last):
  File "wifi_debug_pirai.py", line 37, in <module>
    scheme_embraco.activate()
  File "/usr/local/lib/python2.7/dist-packages/wifi/scheme.py", line 172, in activate
    subprocess.check_output(['/sbin/ifdown', self.interface], stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/sbin/ifdown', 'wlan0']' returned non-zero exit status 1

And also it keeps saving the same scheme in the interfaces file everytime I re-run the script.

How can I handle network names that have spaces between words?

**Comment by rockymeza** [comment]
Hi,
Thanks for bring this up. I think there are some bugs (more than one) in https://github.com/rockymeza/wifi/blob/master/wifi/scheme.py#L196

I could look into this over the weekend, but if you have some time right now that's where I would start looking. There are [some tests related to this as well](https://github.com/rockymeza/wifi/blob/master/tests/test_schemes.py#L61). They seem to work with spaces in the SSID, but perhaps you have spaces in the scheme name?

It might help if you posted your interfaces file after it gets saved (removing your passwords of course).

P.s.

> Hi I am using your wifi and was very happy.

Thank you for saying that! I hope we can get you happy again.

**Comment by robandr** [comment]
Hi Rocky,

You solved my issue! The problems was that I was naming also the scheme
name with spaces. After removing the spaces it worked.
Thanks a lot!

Roberto Andrich
=============================
Sent from Galaxy Note 4
=============================
Am 01.03.2016 20:21 schrieb "Rocky Meza" <notifications@github.com>:

**Comment by rockymeza** [comment]
Thanks for using wifi!

**Comment by robandr** [comment]
Thank you for developing it!!!

Roberto Andrich
=============================
Sent from Galaxy Note 4
=============================
Am 05.03.2016 23:37 schrieb "Rocky Meza" <notifications@github.com>:
